import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Header from '@components/Header'
import Container from '@components/Container'
import Button from '@components/Button'
import styles from '@styles/Home.module.scss'
import products from '@data/products.json'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Store</title>
    
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://app.snipcart.com"></link>
        <link rel="preconnect" href="https://cdn.snipcart.com"></link>
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.css" />
       <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header/>

      <main>
     <Container>
      <h1>Hyper Bros.Trading Cards</h1>
      <h2>Available Cards</h2>

      <ul className={styles.products}>
       {products.map(product=>{

         return (
          <li key={product.id}>
          <Image width="864" height="1200" src={product.image} alt="title"/>
          <h3 className={styles.productTitle}>{product.title}</h3>
          <p className={styles.productPrice}> 
           {`$${product.price}`}
          </p>
          <p>
            <Button className="snipcart-add-item"
  data-item-id={product.id}
  data-item-price={product.price}
  data-item-url="/"//redirect to homepage in order not to have single params on page 
  data-item-description=""
  data-item-image={product.image}
  data-item-name={product.title}>
  Add to cart
{product.title}</Button>
          </p>
          </li>
         )

 
       })}
       
        </ul>
      </Container>

      </main>

      <footer className={styles.footer}>
       &copy; Hipper Bros. Trading Cards, {new Date().getFullYear()}
      </footer>


      <Script src="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.js"/>
<div hidden id="snipcart" data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}/>
    </div>
  )
}
