import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Header from '@components/Header'
import Container from '@components/Container'
import Button from '@components/Button'
import styles from '@styles/Home.module.scss'
// import products from '@data/products.json'

import {
  ApolloClient,
  InMemoryCache,
  gql
} from "@apollo/client";

export default function Home({products}) {
  // console.log(name)
  return (
    <div>
      <Head>
        <title>Store</title>
    
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://app.snipcart.com"></link>
        <link rel="preconnect" href="https://cdn.snipcart.com"></link>
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.css" />
       <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header/>

      <main>
     <Container>
      <h1>Hyper Bros.Trading Cards</h1>
      <h2>Available Cards</h2>

      <ul className={styles.products}>
       {products.map(product=>{
       const {featuredImage} = product;
         return (
          <li key={product.id}>
          <div className={styles.productImage}>
                      <Image width={featuredImage.mediaDetails.width} height={featuredImage.mediaDetails.height} src={featuredImage.sourceUrl} alt={featuredImage.altText} />
                    </div>
                    <h3 className={styles.productTitle}>
                      { product.title }
                    </h3>
                    <p className={styles.productPrice}>
                      {product.productPrice }
                    </p>
          <p>
          <Button
                    className="snipcart-add-item"
                    data-item-id={product.productId}
                    data-item-price={product.productPrice}
                    data-item-url="/"
                    data-item-description=""
                    data-item-image={featuredImage.sourceUrl}
                    data-item-name={product.title}
                    data-item-max-quantity={1}
                  >
  Add to cart
</Button>
          </p>
          </li>
         )

 
       })}
       
        </ul>
      </Container>

      </main>

      <footer className={styles.footer}>
       &copy; Hipper Bros. Trading Cards, {new Date().getFullYear()}
      </footer>


      <Script src="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.js"/>
<div hidden id="snipcart" data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}/>
    </div>
  )
}


export async function getStaticProps(){
  const client = new ApolloClient({
    uri: 'https://ecommerce-web.tastewp.com/graphql',
    cache: new InMemoryCache()
  });

  const response = await client.query({
  query:gql`
    query AllProducts {
      products {
   edges{
  node{
    id
    content
    title
    uri
    product{
      productId
      productPrice
    }
    slug
    featuredImage {
                node {
                  altText
                  sourceUrl
                  mediaDetails {
                    height
                    width
                  }
                }
    }
  }
}
}
}
    `
  })
 //node destructed one level 
 const products = response.data.products.edges.map(({ node }) => {
  const data = {
    ...node,
    ...node.product,
    featuredImage: {
      ...node.featuredImage.node
    }
  }
  return data;
})


  console.log(products)

return {
  props:{
    products
  }
}
// return {
//   props:{
//     name:"masa"
//   }
// }
}